name = "llmentityextractor"
main = "src/index.js"
compatibility_date = "2023-10-30"

[vars]
# LLMFOUNDRY_TOKEN will be set in the Cloudflare dashboard for production

[build]
command = ""  # No build command needed for this project

[[rules]]
type = "Data"
globs = ["**/*.json", "**/*.html"]
fallthrough = true
